config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  resources :athletes, only: [ :index, :show ] do
    resources :weekly_plans, only: [ :create, :new ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assigned_session.rb
class AssignedSession < ApplicationRecord
  belongs_to :athlete

  validates :date, presence: true
  validates :details, presence: true
  validates :session_type, presence: true

  enum :session_type, {
    easy_run: 0,
    workout: 1,
    long_run: 2,
    rest_day: 3,
    cross_training: 4,
    strength: 5
  }
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  has_many :assigned_sessions

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true


  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  def index
    @athletes = Athlete.all
  end

  def show
    @athlete = Athlete.find(params[:id])
    @start_date = Date.current.beginning_of_week
  end
end

app/controllers/weekly_plans_controller.rb
class WeeklyPlansController < ApplicationController
  def new
    @athlete = Athlete.find(params[:athlete_id])
  end

  def create
    @athlete = Athlete.find(params[:athlete_id])

    start_date = params[:athlete][:start_date]

    if start_date.present?

      # Parse the start_date
      date = Date.parse(start_date)

      # Create the 7 new AssignedSession records for the week in memory without saving them
      sessions = []

      7.times do |i|
        session_type_param = params[:athlete]["session_type_#{i}"]
        details_param = params[:athlete]["details_#{i}"]

        sessions << @athlete.assigned_sessions.build(
          session_type: session_type_param,
          date: date + i.days,
          details: details_param
        )
      end

      # Validate all sessions
      if sessions.all?(&:valid?)
        # If all sessions are valid, save them in one transaction
        ActiveRecord::Base.transaction do
          sessions.each(&:save!)
        end

        redirect_to athlete_path(@athlete), notice: "New weekly plan successfully created."

      else
        # If any session is invalid, add errors to the athlete object and re-render the form
        sessions.each_with_index do |session, index|
          if session.invalid?
            session.errors.full_messages.each do |message|
              @athlete.errors.add(:base, "Session #{index + 1}: #{message}")
            end
          end
        end

        # Re-render the form with errors
        render :new, status: :unprocessable_entity
      end


    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/athletes/index.html.erb
<h1 class="mb-4">All Athletes</h1>

<ul class="flex flex-col gap-4 w-full">
  <% @athletes.each do |athlete| %>
    <li class="flex gap-4 items-center justify-between bg-white rounded-lg px-5 py-2">
      <div class="flex gap-4 items-center">
        <span class="rounded-full overflow-hidden">
          <%= image_tag 'user-placeholder.jpg' %>
        </span>
        <%= link_to athlete.full_name, athlete_path(athlete) %>
      </div>
      <p><%= athlete.email %></p>
      
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
      </svg>
    </li>
  <% end %>
</ul>

app/views/athletes/show.html.erb
<div class="grid md:grid-cols-4 gap-4" >
  <section class="flex flex-col gap-4 bg-white rounded-md p-5">
    <span class="rounded-full overflow-hidden">
      <%= image_tag 'user-placeholder.jpg' %>
    </span>
    <h1 class="text-xl font-semibold"><%= @athlete.full_name %></h1> 
  </section>

  <section class="flex flex-col gap-4 bg-white rounded-md p-5 md:col-span-3 shadow">
    <h2 class="text-lg font-bold mb-4">This Week's Training Plan</h2>
    
    <div class="flex flex-wrap gap-4">
      
      <% 7.times do |i| %>
        <div class="flex flex-col p-4 rounded-lg bg-gray-100 text-center border border-gray-300 w-52 min-h-40">
          <h3 class="font-medium text-lg mb-2"><%= (@start_date + i).strftime("%A") %></h3>
          <p class="text-sm text-gray-700"><%= (@start_date + i).strftime("%B %-d, %Y") %></p>
          <% @athlete.assigned_sessions.each do |session| %>
            <% if (@start_date + i) == session.date %>
              <p class="mt-2 text-sm bg-blue-100 text-blue-600 p-2 rounded border border-blue-200"><%= session.details %></p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= link_to "Create plan", new_athlete_weekly_plan_path(@athlete) %>
  </section>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Coaching App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-100">
    <main class="container mx-auto mt-28 px-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/weekly_plans/new.html.erb
<%= link_to "Back to athlete", athlete_path(@athlete) %>
<section class="flex flex-col gap-4 bg-white rounded-md p-5 md:col-span-3 shadow">
  <h2 class="text-lg font-bold mb-4">Add Weekly Plan</h2>
  <%= form_with(model: @athlete, url: athlete_weekly_plans_path(@athlete), method: :post, local: true) do |form| %>
    <div>
      <%= form.label :start_date, 'Select Start Date:' %>
      <%= form.date_field :start_date, default: Date.today %>
      <% if @athlete.errors.full_messages.any? { |msg| msg.include?("Date can't be blank") } %>
        <div class="text-sm text-red-800">
          <%= @athlete.errors.full_messages.select { |msg| msg.include?("Date can't be blank")} %>
        </div>
      <% end %>
    </div>
    <div class="flex flex-wrap gap-4">
      <% 7.times do |i| %>
        <div class="flex flex-col p-4 rounded-lg bg-gray-100 border border-gray-300 w-52 min-h-40">
          <%= form.label :session_type %>
          <%= form.select "session_type_#{i}", AssignedSession.session_types.keys.map { |type| [type.humanize, type] } %>
        
          <%= form.text_area "details_#{i}", placeholder: 'Session details', class: 'mt-2 p-2 border' %>
          <% if @athlete.errors.full_messages.any? { |msg| msg.include?("Session #{i + 1}:") } %>
            <div class="text-sm text-red-800">
              <%= @athlete.errors.full_messages.select { |msg| msg.include?("Session #{i + 1}:") }.join(", ") %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= form.submit 'Create Weekly Plan', class: 'mt-4 bg-blue-500 text-white rounded p-2' %>
  <% end %>
</section>